version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: veggie-store-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: veggie
      POSTGRES_PASSWORD: veggie123
      POSTGRES_DB: veggie_store
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
