[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npx prisma generate && npm run build && npx prisma migrate deploy && npx prisma db seed"

[deploy]
startCommand = "node dist/index.js"
