[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npx prisma generate && npm run build"

[deploy]
startCommand = "node_modules/.bin/prisma migrate deploy && node dist/index.js"
