[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npx prisma generate && npm run build && npx prisma migrate deploy && npx prisma db seed"

[deploy]
startCommand = "npx prisma migrate deploy && (node dist/prisma/seed.js 2>&1 || echo 'Seed skipped') && node dist/index.js"
